; This is to autoboot the program on start-up, on the Pi. CREATE THE SERVICE FILE:

; sudo nano /etc/systemd/system/argus.service

[Unit]
Description=Argus Facial Recognition System
After=multi-user.target sound.target
Wants=sound.target

[Service]
Type=simple
User=mercer
WorkingDirectory=/home/mercer/ECE-428-Final-Project
ExecStart=/usr/bin/python3 /home/mercer/ECE-428-Final-Project/Face_Scan_and_Recog.py
Restart=on-failure
RestartSec=5
ExecStartPre=/bin/sleep 5
Environment=PYTHONUNBUFFERED=1
Environment=PYTHONPATH=/home/mercer/.local/lib/python3.13/site-packages
Environment=XDG_RUNTIME_DIR=/run/user/1000
Environment=PULSE_RUNTIME_PATH=/run/user/1000/pulse

[Install]
WantedBy=multi-user.target
EOF
